In [13]:
import numpy as np
# Create a 1D array of numbers from 10 to 50.
array_1d = np.arange(10, 51)
print(array_1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [14]:
# Create a 3x3 array of random numbers between 0 and 1.
array_3x3 = np.random.rand(3, 3)
print(array_3x3)

[[0.80298135 0.30017309 0.21255277]
 [0.90119944 0.64163912 0.10011833]
 [0.16245244 0.91634015 0.16040641]]


In [15]:
# Find the shape, size, and data type of the array you created in the previous task.
shape = array_3x3.shape
size = array_3x3.size
data_type = array_3x3.dtype
print("Shape:", shape)
print("Size:", size)
print("Data type:", data_type)

Shape: (3, 3)
Size: 9
Data type: float64


In [16]:
# Add 5 to every element of a 1D array.
array_1d_plus_5 = array_1d + 5
print("1D array + 5:", array_1d_plus_5)

1D array + 5: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [17]:
# Multiply two 2D arrays element-wise.
array_3x3_2 = np.random.rand(3, 3)
elementwise_multiplication = array_3x3 * array_3x3_2
print("Element-wise multiplication:\n", elementwise_multiplication)

Element-wise multiplication:
 [[0.49134326 0.16869539 0.14129031]
 [0.15835314 0.57323783 0.03320749]
 [0.07455776 0.33751542 0.15119012]]


In [18]:
# 5x5 array of integers from 1 to 25
array_5x5 = np.arange(1, 26).reshape(5, 5)
print("5x5 array:\n", array_5x5)

# Extract the first row
first_row = array_5x5[0]
print("First row:", first_row)

# Extract the last column
last_column = array_5x5[:, -1]
print("Last column:", last_column)

5x5 array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]


In [19]:
# Subarray of the first three rows and first two columns
subarray = array_5x5[:3, :2]
print("Subarray:\n", subarray)

Subarray:
 [[ 1  2]
 [ 6  7]
 [11 12]]


In [20]:
# 10-element array of random integers between 1 and 100
random_array = np.random.randint(1, 101, 10)
print("Random array:", random_array)

Random array: [25 94 72 76 74 71 68 68 76 34]


In [21]:
# Find max, min, mean, and standard deviation
max_value = random_array.max()
min_value = random_array.min()
mean_value = random_array.mean()
std_dev = random_array.std()
print("Max:", max_value)
print("Min:", min_value)
print("Mean:", mean_value)
print("Std Dev:", std_dev)

Max: 94
Min: 25
Mean: 65.8
Std Dev: 19.548913013259842


In [22]:
# Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix
array_reshaped = np.arange(1, 13).reshape(3, 4)
print("Reshaped 3x4 matrix:\n", array_reshaped)

Reshaped 3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
# 3x3 matrix of ones
matrix_ones = np.ones((3, 3))

# Add a 1D array [1, 2, 3] to each row
broadcasted_matrix = matrix_ones + np.array([1, 2, 3])
print("Broadcasted matrix:\n", broadcasted_matrix)

Broadcasted matrix:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [24]:
# Create a 1D array of random integers between 1 and 50
random_array_filter = np.random.randint(1, 51, 20)
print("Random array for filtering:", random_array_filter)

Random array for filtering: [44 32 24 20 38 12 39 16 50 44 44 46 28 42 26 43  5 45 22 49]


In [25]:
# Extract elements divisible by 5
divisible_by_5 = random_array_filter[random_array_filter % 5 == 0]
print("Elements divisible by 5:", divisible_by_5)

Elements divisible by 5: [20 50  5 45]


In [26]:
# Create two 2x2 matrices and perform matrix multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_multiplication = np.dot(matrix_a, matrix_b)
print("Matrix multiplication result:\n", matrix_multiplication)

Matrix multiplication result:
 [[19 22]
 [43 50]]


In [27]:
# Given a 4x4 array, use fancy indexing to extract diagonal elements
array_4x4 = np.arange(1, 17).reshape(4, 4)
diagonal_elements = array_4x4[[0, 1, 2, 3], [0, 1, 2, 3]]
print("4x4 array:\n", array_4x4)
print("Diagonal elements:", diagonal_elements)

4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]
